<?php

/**
 * @file
 * Install, update and uninstall functions for the front page module.
 */



/**
 * Implements hook_uninstall(). */
function front_page_uninstall() {
  config_clear('front_page.settings', 'front_page_enable');

  foreach (user_roles() as $rid => $role_label) {
    config_clear('front_page.settings', "front_page_role_{$rid}");
  }
}


/**
 * Implements hook_install().
 */
function front_page_install() {
  $config = config('front_page.settings');
  $config->set('front_page_enable', '0');
  $config->set('front_page_home_link_path', '');
  $config->set('front_page_role_rid', '');
  $config->save();
}

