<?php

/**
 *
 * This module allows the site admin to set advanced front page settings.
 *
 * This version is for Backdrop 7. Earlier versions can be found at http://drupal.org/project/front.
 *
 */


/**
 * Implements hook_menu(). */
function front_menu() {
  // Front page settings.
  $items['admin/config/front'] = array(
    'title' => 'Front Page',
    'description' => 'Configure front page.',
    'position' => 'right',
    'weight' => -15,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer front page'),
    'file' => 'system.admin.inc',
    'file path' => backdrop_get_path('module', 'system'),
  );

  $items['admin/config/front/settings'] = array(
    'title' => 'Settings',
    'description' => 'Administer custom front page settings.',
    'weight' => 0,
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('front_admin'),
    'access arguments' => array('administer front page'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'file' => 'front.admin.inc',
  );
  $items['admin/config/front/arrange'] = array(
    'title' => 'Arrange',
    'description' => 'Ability to re-arrange what order front page roles are processed.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('front_admin_arrange_form'),
    'access arguments' => array('administer front page'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'file' => 'front.admin.inc',
    'weight' => 1,
  );
  $items['admin/config/front/home-links'] = array(
    'title' => 'Home links',
    'description' => 'Allows you to change the location of the &lt;front&gt; placeholder.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('front_admin_home_links'),
    'access arguments' => array('administer front page'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'file' => 'front.admin.inc',
    'weight' => 2,
  );
  $items['front'] = array(
    'title' => '',
    'page callback' => 'front',
    'access callback' => TRUE,
    'type' => MENU_SUGGESTED_ITEM,
  );
  return $items;
}

/**
 * Implements hook_permission(). */
function front_permission() {
  return array(
    'administer front page' => array(
      'title' => t('Administer front page'),
      'description' => t('Allow users to make changes to the front page settings.'),
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function front_config_info() {
  $prefixes['front.settings'] = array(
    'label' => t('Front Page settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_init(). */
function front_init() {
  $config = config('front.settings');
  // Make sure front page module is not run when using cli.
  // Make sure front page module does not run when installing Backdrop either.
  if (backdrop_is_cli() || backdrop_installation_attempted()) {
    return;
  }
  // Don't run when site is in maintenance mode
  if (state_get('maintenance_mode', 0)) {
    return;
  }
  // Ignore non index.php requests (like cron)
  if (!empty($_SERVER['SCRIPT_FILENAME']) && realpath(BACKDROP_ROOT . '/index.php') != realpath($_SERVER['SCRIPT_FILENAME'])) {
    return;
  }

  global $_front, $conf;

  //$site_config = config('system.core');
  //$site_frontpage = $site_config->get('site_frontpage');
  
  // let administrator know that there is a config error.
  if (config_get('system.core', 'site_frontpage') == 'front' && user_access('administer menu')) {
    backdrop_set_message(t('There is a configuration error. The home page should not be set to the path "front". Please change this !link', array('!link' => l(t('here'), 'admin/config/system/site-information'))), 'error');
  }

  if ($config->get('front_enable') && backdrop_is_front_page()) {
    $_front = front_get_by_role();
  }

  
  
  $match = array();
  
  if (user_access('administer menu') && preg_match('@^front/preview/([0-9]+)$@', $_GET['q'], $match)) {
    $_front = front_get_by_rid($match[1]);
  }

  if ($_front) {
    // Let other hooks modify
    backdrop_alter('front', $_front);

    switch ($_front['mode']) {
      case 'themed':
      case 'full':
        $_GET['q'] = 'front';
        // need to set variable site_frontpage to current path so that it thinks it is the front page.
        $conf['site_frontpage'] = $_GET['q'];
        break;

      case 'redirect':
        $url = front_parse_url($_front['data']);
        backdrop_goto($url['path'], $url['options']);
        break;

      case 'alias':
        $url = front_parse_url($_front['data']);
        $_GET['q'] = backdrop_get_normal_path($url['path']);
        // need to set variable site_frontpage to current path so that it thinks it is the front page.
        $conf['site_frontpage'] = $_GET['q'];
        break;
    }

    // turn caching off for this page as it is dependant on role.
    $GLOBALS['conf']['cache'] = FALSE;
  }
}

/**
 * Function to handle the display of the front page themed and full types.
 */
function front() {
  // $_front variable should already have been loaded in front_init() function.
  global $_front;

  if ($_front) {
    switch ($_front['mode']) {
      case 'themed':
        return check_markup($_front['data'], $_front['filter_format']);

      case 'full':
        print check_markup($_front['data'], $_front['filter_format']);
        exit;
    }
  }

  // set page not found as there was no themed or full option set for the front page.
  backdrop_not_found();
  exit;
}

/**
 * Function to parse a full URL including GET variables and fragment
 * to an array ready for backdrop_goto(), url(), or l() functions.
 */
function front_parse_url($path) {
  $url['path'] = $path;
  $url['options'] = array();
  $match = array();
  if (preg_match('@^(?P<path>[^?#]+)(\?(?P<query>[^#]*))?(#(?P<fragment>.*))?$@', $path, $match)) {
    $url['path'] = $match['path'];
    if (!empty($match['query'])) {
      foreach (explode('&', $match['query']) as $query_part) {
        list($key, $value) = explode('=', $query_part);
        $url['options']['query'][$key] = $value;
      }
    }
    if (!empty($match['fragment'])) {
      $url['options']['fragment'] = $match['fragment'];
    }
  }

  // if the token module exists then replace any tokens in the path
  if (module_exists('token')) {
    $url['path'] = token_replace($url['path']);
  }

  return $url;
}

/**
 * Function to return the first role enabled in front page, ordered by weight.
 */
function front_get_by_role($index = 0, $number = 1) {
  global $user;

  $roles = array();
  foreach ($user->roles as $rid) {
    $roles[] = front_get_by_rid($rid);
  }
  
  $roles = array_filter($roles);

  if (empty($roles)) {
    return FALSE;
  }

  uasort($roles, '_front_sort');

  return reset($roles);
}

/**
 * Function to return the first role enabled in front page, ordered by weight.
 */
function front_get_by_rid($rid) {
  $role = _front_get_by_rid_with_default($rid);

  return !empty($role['mode']) ? $role : FALSE;
}

/**
 * Function to return all the roles in front page, ordered by weight.
 */
function front_get_all() {
  $roles = array();
  foreach (user_roles() as $rid => $role) {
    $roles[$rid] = _front_get_by_rid_with_default($rid);
  }

  uasort($roles, '_front_sort');

  return $roles;
}

/**
 * Implements hook_page_url_outbound_alter().
 *
 * This alters anything parsed through the url() function to replace the <front> string
 *  with an alternative string instead of the site_frontpage setting.
 */
function front_url_outbound_alter(&$path, &$options, &$original_path) {
  // check if path is set to 'front' as this is our virtual home
  // page and doesn't work properly unless used from home page.
  if ($path == 'front') {
    $original_path = $path = '';
  }
  $newpath = config_get('front.settings', 'front_home_link_path');
  if (($path == '<front>' || empty($path)) && !empty($newpath)) {
    $original_path = $path = $newpath;
  }
}

/**
 * Implements hook_theme().
 */
function front_theme() {
  return array(
    'front_admin_arrange_form' => array(
      'file' => 'front.admin.inc',
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_user_role_delete().
 */
function front_user_role_delete($role) {
  // Delete Front configuration for the role being deleted.
  config_clear('front.settings', "front_role_{$role->rid}");
}

/**
 * Function to return the first role enabled in front page, with defaults.
 */
function _front_get_by_rid_with_default($rid) {
  return config_get('front.settings', "front_role_{$rid}");
}

/**
 * Sort by weight ASC and rid DESC.
 */
function _front_sort($a, $b) {
  $a_value = (is_array($a) && isset($a['weight'])) ? $a['weight'] : 0;
  $b_value = (is_array($b) && isset($b['weight'])) ? $b['weight'] : 0;

  if ($a_value != $b_value) {
    return ($a_value < $b_value) ? -1 : 1;
  }

  $a_value = (is_array($a) && isset($a['rid'])) ? $a['rid'] : 0;
  $b_value = (is_array($b) && isset($b['rid'])) ? $b['rid'] : 0;

  if ($a_value != $b_value) {
    return ($a_value > $b_value) ? -1 : 1;
  }

  return 0;
}
